name: Windows conda installation

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Windows conda installation
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        auto-activate-base: [true, false]

    steps:

    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: ${{ matrix.auto-activate-base }}
        activate-environment: ""

    - name: Create and update environment
      run: |
        .\create-env.bat
        .\update-env.bat
