name: Build LaTeX document

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -bibtex-
          working_directory: ./_internal
          root_file: Vorbereitung-auf-das-Seminar.tex

      - name: Upload LaTeX document
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ./_internal/Vorbereitung-auf-das-Seminar.pdf
